/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Gunawan Widya Nugraha
 */
 
package Master;
//import program_siswa.mainmenu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement; 
import java.sql.*;
import java.awt.*;
import java.awt.event.*;
import com.mysql.cj.jdbc.Driver;
import com.mysql.jdbc.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.JOptionPane;
 
public class nilai extends javax.swing.JFrame {

    /**
     * Creates new form nilai
     */
    public nilai() {
        initComponents();
        tglskrg();
        tampil_nis();
        tampil_nip();
        this.setSize(1025,680);
        tabel.setModel(tblModel);
        //Tabel(tabel, new int[]{120,180,120,120});
        setDefaultTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    //MENAMPILKAN TANGGAL
    public void tglskrg(){
    java.util.Date skrg= new java.util.Date();
    SimpleDateFormat format= new SimpleDateFormat("dd MMMM yyyy");
    String tgl = format.format(skrg);
    txttgl.setText(format.format(skrg));
    }
    
    
    String data[]=new String[9];
    //KONEKSI KE DATABASE
    public void setDefaultTable() {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try {
    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
    //memanggil variable hubung
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    String SQL = "Select * from nilai";
    //res = variable
    ResultSet res = stt.executeQuery(SQL);
    while(res.next()) {
    //digunakan untuk mengisi data tabel
    data[0] = res.getString(1);
    data[1] = res.getString(2);
    data[2] = res.getString(3);
    data[3] = res.getString(4);
    data[4] = res.getString(5);
    data[5] = res.getString(6);
    data[6] = res.getString(7);
    data[7] = res.getString(8);
    data[8] = res.getString(9);
    tblModel.addRow(data);
    }
    res.close();
    stt.close();
    kon.close();
    } catch(Exception exc) {
    System.err.println(exc.getMessage());
    }
    }
    
    //MEMBUAT PENGATURAN TABEL
    private javax.swing.table.DefaultTableModel tblModel = getDefaultTabelModel();
    private void Tabel(javax.swing.JTable tb, int lebar[]) {
    tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    int kolom=tb.getColumnCount();
    for(int i=0;i < kolom;i++) {
    javax.swing.table.TableColumn tbc = tb.getColumnModel().getColumn(i);
    tbc.setPreferredWidth(lebar[i]);
    tb.setRowHeight(17);
    }
    }
    private javax.swing.table.DefaultTableModel getDefaultTabelModel(){
    return new javax.swing.table.DefaultTableModel(
    new Object [][]{},
    //digunakan untuk menampilkan judul table
    new String []{"KODE NILAI","NIS","NIP","NILAI UH","NILAI PRAKTEK","NILAI PTS","NILAI PAS","TOTAL NILAI","RATA NILAI"}
    ){
    boolean[] canEdit = new boolean []{
    false, false, false, false
    };
    public boolean isCellEditable(int rowIndex, int columnIndex) {
    return canEdit [columnIndex];
    }
    };
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    int row = 0;
    public void Tampil(){
    row = tabel.getSelectedRow();
    kodenilai.setText(tblModel.getValueAt(row,0).toString());
    tnis.setSelectedItem(tblModel.getValueAt(row,1).toString());
    tnip.setSelectedItem(tblModel.getValueAt(row,2).toString());
    nilaiuh.setText(tblModel.getValueAt(row,3).toString());
    nilaipraktek.setText(tblModel.getValueAt(row,4).toString());
    nilaipts.setText(tblModel.getValueAt(row,5).toString());
    nilaipas.setText(tblModel.getValueAt(row,6).toString());
    totalnilai.setText(tblModel.getValueAt(row,7).toString());
    rata_nilai.setText(tblModel.getValueAt(row,8).toString());
    }
    
    @SuppressWarnings("unchecked")
        public void tampil_nis(){
        String hubung="jdbc:mysql://localhost:3306/sekolah";
        try{
        Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
        Connection con=DriverManager.getConnection(hubung,"root","");
        Statement stt=con.createStatement();
        String sql = "Select NIS from siswa order by NIS asc";
        ResultSet res= stt.executeQuery(sql);
        while(res.next()){
        Object[] ob = new Object[1];
        ob[0] = res.getString(1);
        tnis.addItem(ob[0]);
        }
        res.close();
        stt.close();
        con.close();
        } catch(Exception exc){
        System.err.println(exc.getMessage());}
}
// <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        simpan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txttgl = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tnip = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tnis = new javax.swing.JComboBox();
        kodenilai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        tb = new javax.swing.JLabel();
        ta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nilaiuh = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nilaipraktek = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        nilaipts = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nilaipas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalnilai = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rata_nilai = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM NILAI");

        txttgl.setText("22 September 2005");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Date:");

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Nilai", "NIS", "NIP", "Nilai UH", "Nilai Praktek", "Nilai PTS", "Nilai PAS", "Total Nilai", "Rata Nilai"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        ubah.setText("UBAH");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        keluar.setText("KELUAR");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("© XI-RPL 2 - Gunawan Widya Nugraha");

        tnip.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih NIP" }));
        tnip.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tnipItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("NIP");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setText("NIS");

        tnis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih NIS" }));
        tnis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tnisItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("KODE NILAI");

        tc.setText("Data");

        tb.setText("Data");

        ta.setText("Data");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setText("NILAI UH");

        nilaiuh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiuhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("NILAI PRAKTEK");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("NILAI PAS");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setText("NILAI PTS");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("TOTAL NILAI");

        totalnilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalnilaiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("RATA-RATA NILAI");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(kodenilai, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(ta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tnis, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(tb)
                                        .addGap(223, 223, 223))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nilaiuh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nilaipraktek, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nilaipts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nilaipas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(totalnilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(rata_nilai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tnip, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ubah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(simpan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(45, 45, 45))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(tc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txttgl))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nilaiuh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nilaipraktek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nilaipts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(nilaipas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(totalnilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(rata_nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(100, 100, 100))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttgl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kodenilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tnip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(368, 368, 368)))
                .addComponent(jLabel15)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String SQL;
    //ref_nis untuk muncul data nama
public void ref_nis()
    {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try
    {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    SQL = "SELECT nama FROM siswa WHERE NIS = '"+tnis.getSelectedItem()+"'";
    ResultSet rs = stt.executeQuery(SQL);
    while(rs.next())
    {
    ta.setText(rs.getString(1));
    }
    }
    catch(Exception e)
    {
    System.out.print(e);
    }
}

public void tampil_nip(){
    String hubung="jdbc:mysql://localhost:3306/sekolah";
    try{
    Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
    Connection con=DriverManager.getConnection(hubung,"root","");
    Statement stt=con.createStatement();
    String sql = "Select nip from guru order by nip asc";
    ResultSet res= stt.executeQuery(sql);
    while(res.next()){
    Object[] ob = new Object[1];
    ob[0] = res.getString(1);
    tnip.addItem(ob[0]);
    }
    res.close();
    stt.close();
    con.close();
    } catch(Exception exc){
    System.err.println(exc.getMessage());}
}
// <editor-fold defaultstate="collapsed" desc="Generated Code">
public void ref_nip()
    {
    String hubung = "jdbc:mysql://localhost:3306/sekolah";
    try
    {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection kon = DriverManager.getConnection(hubung,"root","");
    Statement stt = kon.createStatement();
    SQL = "SELECT nama_guru,nama_mapel FROM guru WHERE nip = '"+tnip.getSelectedItem()+"'";
    ResultSet rs = stt.executeQuery(SQL);
    while(rs.next())
    {
    tb.setText(rs.getString(1));
    tc.setText(rs.getString(2));
    }
    }
    catch(Exception e)
    {
    System.out.print(e);
    }
}
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JFrame form = new JFrame();
        form.setSize(290, 100);
        new nilai(this);
        setTitle("Data Nilai");
    }//GEN-LAST:event_formWindowActivated

    private void totalnilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalnilaiActionPerformed
        // TODO add your handling code here:
        //TOTALNILAI
    }//GEN-LAST:event_totalnilaiActionPerformed

    private void nilaiuhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiuhActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_nilaiuhActionPerformed

    private void tnisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tnisItemStateChanged
        // TODO add your handling code here:
        ref_nis();
    }//GEN-LAST:event_tnisItemStateChanged

    private void tnipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tnipItemStateChanged
        // TODO add your handling code here:
        ref_nip();
    }//GEN-LAST:event_tnipItemStateChanged

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        int num1 = Integer.parseInt(nilaiuh.getText());
        int num2 = Integer.parseInt(nilaipraktek.getText());
        int num3 = Integer.parseInt(nilaipts.getText());
        int num4 = Integer.parseInt(nilaipas.getText());
        int total = num1 + num2 + num3 + num4;
        int rata_rata = total / 4;
        totalnilai.setText(Integer.toString(total));
        rata_nilai.setText(Integer.toString(rata_rata));

        String text = nilaiuh.getText();
        if (text == null || text.isEmpty()) {
            JFrame frame = new JFrame("Error Popup Example");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

            // Create and display an error message dialog
            JOptionPane.showMessageDialog(frame, "An error occurred!", "Error", JOptionPane.ERROR_MESSAGE);

            frame.setSize(300, 200);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_tambahActionPerformed

//    public void MainMenu() {
//        new MainMenu().setVisible(true);
//    }
    
    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        //      new MainMenu().setVisible(false);
    }//GEN-LAST:event_keluarActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "delete from nilai where kode_nilai='"+kodenilai.getText()+"'";
            stt.executeUpdate(SQL);
            tblModel.removeRow(row);
            kodenilai.setText("");
            nilaiuh.setText("");
            nilaipraktek.setText("");
            nilaipas.setText("");
            nilaipts.setText("");
            totalnilai.setText("");
            rata_nilai.setText("");
            ta.setText("");
            tb.setText("");
            tc.setText("");
            //cmbjurusan.setSelectedItem("-=List Jurusan=-");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();
            String SQL = "update nilai set nuh='"+nilaiuh.getText()+"',np='"+nilaipraktek.getText()+"',npts='"+nilaipts.getText()+"',npas='"+nilaipas.getText()+"' where kode_nilai='"+kodenilai.getText()+"'";
            stt.executeUpdate(SQL);
            data[0]=kodenilai.getText();
            data[1]=tnis.getSelectedItem().toString();
            data[2]=tnip.getSelectedItem().toString();
            data[3]=nilaiuh.getText();
            data[4]=nilaipraktek.getText();
            data[5]=nilaipts.getText();
            data[6]=nilaipas.getText();
            data[7]=totalnilai.getText();
            data[8]=rata_nilai.getText();
            tblModel.removeRow(row);
            tblModel.insertRow(row, data);
            kodenilai.setText("");
            tnis.setSelectedItem("-=NIS=-");
            tnip.setSelectedItem("-=NIP=-");
            nilaiuh.setText("");
            nilaipraktek.setText("");
            nilaipts.setText("");
            nilaipas.setText("");
            totalnilai.setText("");
            rata_nilai.setText("");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }
    }//GEN-LAST:event_ubahActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        // Digunakan untuk menampilkan data yang sudah ada pada table dgn klik 2x mouse
        if(evt.getClickCount()==2){
            Tampil();
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        try {
            String hubung = "jdbc:mysql://localhost:3306/sekolah";
            Class.forName("com.mysql.cj.jdbc.Driver").newInstance();
            Connection kon = DriverManager.getConnection(hubung,"root","");
            Statement stt = kon.createStatement();

            String checkSQL = "SELECT * FROM nilai WHERE kode_nilai = '" + kodenilai.getText() + "'";
            ResultSet rs = stt.executeQuery(checkSQL);

            if (rs.next()) {
                //A record with the same primary key already exists
                JOptionPane.showMessageDialog(this, "Kode nilai " + kodenilai.getText() + " sudah digunakan");
            } else {
                String SQL = "insert into nilai values('"+kodenilai.getText()+"','"+tnis.getSelectedItem()+"','"+tnip.getSelectedItem()+"','"+nilaiuh.getText()+"','"+nilaipraktek.getText()+"','"+nilaipts.getText()+"','"+nilaipas.getText()+"','"+totalnilai.getText()+"','"+rata_nilai.getText()+"')";
                stt.executeUpdate(SQL);
                data[0]=kodenilai.getText();
            }
            data[1]=tnis.getSelectedItem().toString();
            data[2]=tnip.getSelectedItem().toString();
            data[3]=nilaiuh.getText();
            data[4]=nilaipraktek.getText();
            data[5]=nilaipts.getText();
            data[6]=nilaipas.getText();
            data[7]=totalnilai.getText();
            data[8]=rata_nilai.getText();
            tblModel.insertRow(0, data);
            kodenilai.setText("");
            tnis.setSelectedItem("-=NIS=-");
            tnip.setSelectedItem("-=NIP=-");
            nilaiuh.setText("");
            nilaipraktek.setText("");
            nilaipts.setText("");
            nilaipas.setText("");
            totalnilai.setText("");
            rata_nilai.setText("");
            stt.close();
            kon.close();
        } catch(Exception exc) {
            System.err.println(exc.getMessage());
        }

    }//GEN-LAST:event_simpanActionPerformed

    
    //MEMBUAT FRAME DI TENGAH
    public nilai(JFrame form) {
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    int x = (dim.width-form.getSize().width)/2;
    int y = (dim.height-form.getSize().height)/2;
    form.setLocation(x,y);
    }
    /**
     * @param args the command line arguments
     */
    
    public class ErrorPopupExample {
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(nilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new nilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField kodenilai;
    private javax.swing.JTextField nilaipas;
    private javax.swing.JTextField nilaipraktek;
    private javax.swing.JTextField nilaipts;
    private javax.swing.JTextField nilaiuh;
    private javax.swing.JTextField rata_nilai;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel ta;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JLabel tb;
    private javax.swing.JLabel tc;
    private javax.swing.JComboBox tnip;
    private javax.swing.JComboBox tnis;
    private javax.swing.JTextField totalnilai;
    private javax.swing.JLabel txttgl;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
